---
title: "HW2.Rmd"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the Data Again
As a reminder, during EDA we compressed a field, LAW_CAT_CD, which had 3 classes of crime, FELONY, MISDEMEANOR, VIOLATION into a binary categorization called FELONY, 1 if a felony, 0 if not.This is our class field.

```{r Load Data}
cdata <- read.csv("cdata.csv")
cdata <- subset(cdata, select = -c(X))
length(cdata)
```



```{r RandomForest TT-Split}
set.seed(777)
train_pct = .05
split <- sample(c(TRUE, FALSE), nrow(cdata), replace=TRUE, prob=c(train_pct,(1-train_pct)))

cdTrain <- cdata[split,]
cdTest <- cdata[!split,]
nrow(cdTrain)
nrow(cdTest)
```
```{r RandomForest}
library(randomForest)

# Run RandomForest on the CDTrain dataset
rf_m <- randomForest(FELONY ~ ., data = cdTrain)
rf_p <- predict(rf_m, newdata = cdTest)
rf_p <- ifelse(rf_p > 0.5,1,0) # Probability check
CM = table(cdTest[,124] , rf_p)
print(CM)
err_metric(CM)

# Print the model summary
print(model)
```

```{r CV TT-Split}
set.seed(777)
train_pct = .3
split <- sample(c(TRUE, FALSE), nrow(cdata), replace=TRUE, prob=c(train_pct,(1-train_pct)))

cdTrain <- cdata[split,]
cdTest <- cdata[!split,]
nrow(cdTrain)
nrow(cdTest)
```

```{r CV}
# Perform cross-validation using the caret package
library(caret)
fitControl <- trainControl(method = "cv", number = 10) # 10-fold cross-validation
cv_m <- train(FELONY ~ ., data = cdTrain, method = "glm", trControl = fitControl)

# Evaluate the model on the test set
cv_p <- predict(cv_m, cdTest)
cv_p <- ifelse(cv_p > 0.5,1,0) # Probability check
CM = table(cdTest$FELONY , cv_p)
print(CM)
err_metric(CM)

```
```{r Bagging TT-Split}
set.seed(777)
train_pct = .05
split <- sample(c(TRUE, FALSE), nrow(cdata), replace=TRUE, prob=c(train_pct,(1-train_pct)))

cdTrain <- cdata[split,]
cdTest <- cdata[!split,]
nrow(cdTrain)
nrow(cdTest)
```

```{r Bagging}
library(caret)

# Create bagging model
bg_m <- train(FELONY ~ ., data = cdTrain, method = "bag")

# Generate predictions on test data
bg_p <- predict(bg_m, cdTest)
bg_p <- ifelse(loocv_p > 0.5,1,0) # Probability check
CM = table(cdTest$FELONY , loocv_p)
print(CM)
err_metric(CM)
```

```{r Boosting}
library(caret)
library(xgboost)
cdmTrain <- as.matrix(cdTrain)
cdmTest <- as.matrix(cdTest)

bst_m <- xgboost(data = cdmTrain,
                label = cdmTrain[,124],
                nrounds = 2,
                objective = "binary:logistic")

bst_p <- predict(bst_m, cdmTest)
bst_p <- ifelse(bst_p > 0.5,1,0) # Probability check
CM = table(cdTest$FELONY , bst_p)
print(CM)
err_metric(CM)
```
